# Generated by Django 4.1.7 on 2023-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phon_code',
            field=models.IntegerField(null=True),
        ),
    ]
