# Generated by Django 4.1.7 on 2023-08-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_phon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phon_code',
        ),
        migrations.CreateModel(
            name='PhonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phon_code', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_sms_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
