# Generated by Django 4.1.7 on 2023-08-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlienInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_invite_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
