# Generated by Django 4.1.7 on 2023-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alieninvitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alieninvitecode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
