# Generated by Django 4.1.7 on 2023-08-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_alieninvitecode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alieninvitecode',
            old_name='code',
            new_name='alien_invite_code',
        ),
    ]
