# Generated by Django 4.1.7 on 2023-08-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alieninvitecode_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alieninvitecode',
            name='alien_invite_code',
            field=models.CharField(max_length=6),
        ),
    ]
