# Generated by Django 4.1.7 on 2023-08-08 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_alieninvitecode_alien_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alieninvitecode',
            name='user',
        ),
        migrations.AddField(
            model_name='alieninvitecode',
            name='code_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_invite_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
