# Generated by Django 4.1.7 on 2023-08-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_alieninvitecode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alieninvitecode',
            name='code_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL),
        ),
    ]
