# Generated by Django 4.1.7 on 2023-08-08 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_alieninvitecode_code_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alieninvitecode',
            old_name='alien_invite_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='alieninvitecode',
            name='code_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_invite_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
