# Generated by Django 4.1.7 on 2023-08-08 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_alien_invite_code_alieninvitecode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alieninvitecode',
            name='code_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alien_invite_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
