# Generated by Django 4.1.7 on 2023-08-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alieninvitecode_phone_number_user_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alieninvitecode',
            name='phone_number_user_code',
        ),
    ]
