# Generated by Django 4.1.7 on 2023-08-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_owneruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerUser',
        ),
    ]
